export default  [
  {
    id:'gameMatch',
    form:[
      [{
      label:'Derniers Matchs',
      html:'h2',
      className:'',
      }],
      [{
      label:'Derniers Matchs',
      html:'input',
      id:'game',
      className:'',
      match:/^.+$/
      },
      {
      label:'Equipes',
      html:'input',
      id:'score',
      className:'',
      match:/^\d+$/
      }]
    ]
  },
  {
    id:'editUser',
    props:['match.params.userId:_id'],
    form:[
      [{
        label:"Editer cet Utilisateur",
        html:'h2',
        className:'',
      }],
      [{
        label:'Prénom',
        html:'input',
        id:'firstName',
        className:'',
        match:/^.+$/
      },
      {
        label:'Nom',
        html:'input',
        id:'lastName',
        className:'',
        match:/^\d+$/
      }],
      [{
        label:'Adresse',
        html:'input',
        id:'address',
        className:'',
        match:/^.+$/
      },
      {
        label:'Téléphone',
        html:'input',
        id:'phone',
        className:'',
        match:/^(?:(?:\+|00)33[\s.-]{0,3}(?:\(0\)[\s.-]{0,3})?|0)[1-9](?:(?:[\s.-]?\d{2}){4}|\d{2}(?:[\s.-]?\d{3}){2})$/
      }],
      [{
        label:'Soumettre',
        html:'submit',
        id:'submit',
        className:'',
        match:/^.+$/
      }]
    ]
  },
  {
    id:'addUser',
    form:[
      [{
        label:"Ajout d'Utilisateur",
        html:'h2',
        className:'',
      }],
      [{
        label:'Prénom',
        html:'input',
        id:'firstName',
        className:'',
        match:/^.+$/
      },
      {
        label:'Nom',
        html:'input',
        id:'lastName',
        className:'',
        match:/^\d+$/
      }],
      [{
        label:'Adresse',
        html:'input',
        id:'address',
        className:'',
        match:/^.+$/
      }],
      [{
        label:'Soumettre',
        html:'submit',
        id:'submit',
        className:'',
        match:/^.+$/
      }]
    ]
  },
  {
    id:'addCotisation',
    form:[
      [{
        label:"Ajout de Cotisation",
        html:'h2',
        className:'',
      }],
      [{
        label:'Date de Début',
        html:'input',
        id:'start',
        className:'',
        match:/^.+$/
      },
      {
        label:'Date de Fin',
        html:'input',
        id:'end',
        className:'',
        match:/^\d+$/
      }],
      [{
        label:'Montant',
        html:'input',
        id:'address',
        className:'',
        match:/^.+$/
      },
      {
        label:'Mode de Paiement',
        html:'input',
        id:'address',
        className:'',
        match:/^.+$/
      }],
      [{
        label:'Créer la cotisation',
        html:'submit',
        id:'submit',
        className:'',
        match:/^.+$/
      }]
    ]
  },
  {
    id:'addTransactionUser',
    props:['match.params.userId:from'],
    form:[
      [{
        label:"Nouvelle Transaction",
        html:'h2',
        className:'',
      }],
      [{
        label:'Destinataire',
        html:'autocomplete',
        collection:'users',
        returned:['_id:to'],
        displayed:['firstName',' ','lastName'],
        id:'to',
        className:'',
        match:/^.+$/
      }],
      [{
        label:'Montant €',
        html:'input',
        id:'std_currency',
        className:'',
        match:/^.+$/
      },
      {
        label:'Montant MLC',
        html:'input',
        id:'mlc',
        className:'',
        match:/^.+$/
      }],
      [{
        label:'Date Effective',
        html:'datepicker',
        id:'createdAt',
        className:'',
        match:/^.+$/
      }],
      [{
        label:'Créer la Transaction',
        html:'submit',
        id:'submit',
        className:'',
        match:/^.+$/
      }]
    ]
  },

]
